### ISSUE TITLE
Standard mechanism to skip questions

### ISSUE THREAD

**Issue by pwim** [SachaG/tokyodev#1]
Could then remove "Prefer not to disclose" from Gender question.

**Comment by SachaG** [comment]
This is how I see it working from a UI/UX point of view:

![https://p198.p4.n0.cdn.getcloudapp.com/items/DOuPj0YL/87a504e6-97ae-4c24-af5d-5878a9cdbf22.gif?v=3777b878fa7eb140326a1304d6325d74](https://p198.p4.n0.cdn.getcloudapp.com/items/DOuPj0YL/87a504e6-97ae-4c24-af5d-5878a9cdbf22.gif?v=3777b878fa7eb140326a1304d6325d74)

I put it in the bottom right to: 

- make sure people actually read the question before skipping it
- recall the placement of the "skip ads" button on YouTube
- not add too much visual clutter to the title, description, etc. part of the question

On the back-end, I think skipping a question would probably just set a `skipped: true` flag. This way we can get data on which questions get skipped the most, too.

**Comment by pwim** [comment]
Looks good to me!
