### ISSUE TITLE
New Questions

### ISSUE THREAD

**Issue by SachaG** [SachaG/tokyodev#10]
Brainstorming some ideas for additional questions/topics we could consider adding. 

- How/where did respondents learn to code? University, bootcamps, etc. 
- What are the biggest pain points of working in Japan? (or: of your current job?)
- What are the nicest perks of working in Japan? (or: of your current job?)
- Are you satisfied with your current visa status?
- Have you ever considered launching your own company in Japan?
- What kind of events/meetups do you attend?
- What developer communities are you part of?
- How did you hear about the survey?
- Have you considered/had other careers besides developer?
- Have you worked as a developer in countries other than Japan, and if so how did it compare?
- What's your favorite omiyage? (or other "fun/weird" questions)

**Comment by pwim** [comment]
> How/where did respondents learn to code? University, bootcamps, etc.

This overlaps with "Have you completed any of the following professional qualifications?" I'd be open to replacing this question with that one, as it is potentially more interesting.

> What are the biggest pain points of working in Japan? (or: of your current job?)
> What are the nicest perks of working in Japan? (or: of your current job?)

Kind of similar to last year's "[What could your employer do to improve your job satisfaction?](https://www.tokyodev.com/insights/2022-developer-survey#how-to-improve-satisfaction)".

Asking about "Japan" more generally could be interesting. I had been focused on people's own experiences, but perhaps casting a wider net gives us some good data on general impressions people have.

> What kind of events/meetups do you attend?
> What developer communities are you part of?

These two questions overlap. Asking one might be interesting, and also a good potential way to get the events / communities to promote the survey.

> Have you worked as a developer in countries other than Japan, and if so how did it compare?

Could be interesting as an interview question, but probably people have too diverse experiences here for us to show as data.

**Comment by SachaG** [comment]
I think this can cover the pain points/perks questions:

<img width="751" alt="Screenshot 2023-09-26 at 16 30 08" src="https://github.com/SachaG/tokyodev/assets/358832/0b4f970a-28d4-446f-8b28-aef5875fd7e8">

And I also added this question about communities: 

<img width="743" alt="Screenshot 2023-09-26 at 16 31 02" src="https://github.com/SachaG/tokyodev/assets/358832
/caeab689-9b9e-47ae-b4d4-888b3f9f8be3">

As well as this one to help us track how people heard about the survey:

<img width="733" alt="Screenshot 2023-09-26 at 16 31 36" src="https://github.com/SachaG/tokyodev/assets/358832/4add94ce-d4a9-4876-a3c8-3f677d66f891">

Any other questions we should consider? What about fun/silly questions to close out the survey?

**Comment by pwim** [comment]
> Any other questions we should consider? What about fun/silly questions to close out the survey?

What physical keyboard layout do you use?

- ANSI (used by America, Australia, Canada and also many Middle-Eastern and Asian countries)
- ISO (used by most European countries and South America)
- JIS (used in Japan)

**Comment by SachaG** [comment]
<img width="736" alt="Screenshot 2023-09-28 at 13 11 24" src="https://github.com/SachaG/tokyodev/assets/358832/d61811e4-75ee-4b05-b674-d318d5d75c7b">

I simplified the keyboard question a bit, what do you think?

**Comment by pwim** [comment]
I had been intending to ask about physical keyboard layout as there's a number of different ways your can define the layout (e.g. QWERTY vs DVORAK), but I think those two are the most common options, so we can go with them

Let's rename the "Japan (JIS) Keyboard Layout" to "Japanese Keyboard Layout".
