### ISSUE TITLE
Dual citizenship

### ISSUE THREAD

**Issue by pwim** [SachaG/tokyodev#19]
Add a note like "If you have multiple nationalities, please choose one arbitrarily." to the nationality question.

**Comment by SachaG** [comment]
The wording feels a bit awkward to me, but I can't say I have anything better to suggest… I guess we could always add a second "Country or Region" question for people who do have a second nationality?

**Comment by SachaG** [comment]
ChatGPT suggested "If you have multiple nationalities, please choose one as you see fit." which I do think is better. What do you think?

**Comment by pwim** [comment]
As theoretically there's no limit on the number of nationalities someone can hold, the proper solution would be to allow someone to select multiple nationalities from a list (e.g. a select with multiple option). If that's not easy to support though though, I'm fine with just having a message.  A simpler wording would be:

> If you have multiple nationalities, please choose one.
