### ISSUE TITLE
Remove emoji from "None of the above"

### ISSUE THREAD

**Issue by pwim** [SachaG/tokyodev#28]
> None of the above has a 🚫 emoji, and is the only one, so seems out of place.

**Comment by SachaG** [comment]
This was to highlight that option visually to help respondents find it, and also because it has special behavior attached (it disables all other checkboxes). If you'd rather remove it it's not a problem though.

**Comment by pwim** [comment]
Two different people noted it was "odd". Maybe that's fine though. I'll leave it to you to decide if it should be removed.

**Comment by SachaG** [comment]
I think we can keep it for now, as it's not something I've heard too many other people have trouble with on the other surveys.
