### ISSUE TITLE
Client side validation of number inputs

### ISSUE THREAD

**Issue by pwim** [SachaG/tokyodev#36]
If I enter text into a number field (e.g. "21 years"), it won't be saved. A minor thing, but it'd be nice if there was some client-side validation to show this is an error.

Similar validation could be added for the email at the end.

**Comment by SachaG** [comment]
I just spent an hour on this… it was trickier than it looked! I'll also look at the email.

**Comment by SachaG** [comment]
I might leave the email as it is for now, because it's a bit trickier to do right.
