### ISSUE TITLE
Professional Qualifications

### ISSUE THREAD

**Issue by pwim** [SachaG/tokyodev#42]
- Add "Some college/university study without earning a degree"
- Repeat the descriptions of the choices from previous questions?
- Is there a way to emphasize the difference with the previous question? It'd be repetitive, but we could add "in computer science (or related fields)" to the options for instance. As is, I worry people will get confused and put the same answer for both (even when they are actually different).

**Comment by SachaG** [comment]
<img width="695" alt="Screenshot 2023-10-03 at 14 00 13" src="https://github.com/SachaG/tokyodev/assets/358832/363c7311-5f90-416f-8986-71585b3369a3">
