### ISSUE TITLE
Quick link for Salary facet?

### ISSUE THREAD

**Issue by pwim** [SachaG/tokyodev#65]
This is likely. what people are most interested in comparing

**Comment by SachaG** [comment]
We could add a "variant" tab to charts where it's relevant that shows the salary facet?

<img width="1084" alt="Screenshot 2023-10-19 at 16 07 53" src="https://github.com/SachaG/tokyodev/assets/358832/a377001f-621c-4bb6-bb55-124e24e02d0d">

We'd probably want to default to the "average" view?

**Comment by pwim** [comment]
Wow, why didn't I think of asking for that! That would be absolutely fabulous.

I think percentiles gives a more accurate view of things than averages (excludes outliers), so would make the most sense for a default.

**Comment by pwim** [comment]
Also, if we do this we can eliminate all the other graphs that we're embedding like "Salary Percentiles by Gender" and "Salary Percentiles by Age".
