### ISSUE TITLE
Filter out "Outside of Japan" respondents

### ISSUE THREAD

**Issue by pwim** [SachaG/tokyodev#66]
I noticed that less people appear to be residing in Tokyo with this years survey. Part of the reason is that we're including "Outside of Japan" respondents in this years data. I'd like to exclude anyone who chose that from our data set entirely.

**Comment by SachaG** [comment]
I think the easiest way to do this would probably to add a one-time script that just takes all those responses out from the final dataset. So they won't be available in the API either but that's probably ok?

**Comment by pwim** [comment]
Okay, sure. If you're removing if from the DB, rather than filtering the responses out, please make a backup first. :wink:

**Comment by SachaG** [comment]
Well the nice thing is that we have two databases, so I can remove it from the "processed" responses while leaving it in the "raw" responses. This way if we change our mind we just run the normalization script again without the filtering.

**Comment by pwim** [comment]
Cool. That works.
