### ISSUE TITLE
Age % of question respondents chart incorrect

### ISSUE THREAD

**Issue by pwim** [SachaG/tokyodev#68]
<img width="784" alt="Screenshot 2023-10-19 at 15 50 40" src="https://github.com/SachaG/tokyodev/assets/30756/929bd4f6-504d-4c7e-870b-2bd9dc45055d">

Adding up everything, I get 84.8%.

**Comment by pwim** [comment]
Professional Software Development Experience has the same issue of the percentages not adding up. Maybe there's an error in your grouping code?

**Comment by SachaG** [comment]
That's probably what's going on yeah. Maybe it's due to including/not including people who didn't answer a question? I'll look into it.

**Comment by SachaG** [comment]
Oh I think it's a problem with how the bounds for each group are defined. When defining groups as options for the survey, if your groups are "20 to 25 years old", "25 to 30 years old", etc. people that are exactly 25 years old might become confused, so I started doing "20 to 24", "25 to 29", etc.

But when using groups to group together results, if you do that then some datapoints can slip through the cracks (for example `24.5`). So I guess I need to differentiate the two scenarios without making the whole thing too confusing…

**Comment by pwim** [comment]
I think I just converted all answers to integers, so 24.5 goes into the 20 to 24 category.

**Comment by SachaG** [comment]
I just tweaked the upper/lower bounds so that even though the group is called `range_20_24` the upper bound is `25` (non-inclusive) and not `24`. It might be a bit confusing when reading the code but other than that it works.
