### ISSUE TITLE
Side by side charts and salary breakdown

### ISSUE THREAD

**Issue by pwim** [SachaG/tokyodev#74]
It'd be great if we could do side-by-side comparison charts for the salary breakdown. That'd allow us to show how the combination of gender and salary is correlated to compensation.

**Comment by SachaG** [comment]
Can you give me an example? Do you mean this view? (disregarding the fact that it doesn't handle the "insufficient data" buckets yet)

<img width="951" alt="Screenshot 2023-10-23 at 20 51 10" src="https://github.com/SachaG/tokyodev/assets/358832/206bf6d0-3705-45da-878d-42cf1d4a048f">

**Comment by pwim** [comment]
If I go to "Salary Breakdown", and then customize the chart, I see an option for "side by side". It raises an error right now.

I thought there was a way to show two versions of this chart:

<img width="931" alt="Screenshot 2023-10-24 at 11 37 51" src="https://github.com/SachaG/tokyodev/assets/30756/3de52f90-4441-43e1-97d7-ccd5bc0b4a29">

A default one, plus one where the gender is restricted to women. Don't see that anymore though.

My goal would be to compare what men and women earn, adjusted for experience.

Women earn less then men. Women are also less experienced then men. So I want to be able to take that into account in a single chart.

**Comment by SachaG** [comment]
Oh ok, did you mean as part of the chart customization options in that "side by side" panel? Or as a pre-calculated tab similar to "salary breakdown"? I'll fix the bug in any case.

**Comment by pwim** [comment]
I'm not quite sure what the difference are between those. Maybe fix the bug, and I can tell you if it solves it?

**Comment by SachaG** [comment]
The data for the "Salary Breakdown" tabs is pre-calculated at build time just like the data for the main, non-filtered tabs. 

On the other hand if you bring up the "customize chart" panel to query the API live you can enter any parameter you want. 

That being said you can't really combine filters and facets currently (although I don't think it would be impossible to add) so I'm thinking we should probably remove the ability to customize the "Salary Breakdown" charts as it will either break; or even if did work it would give you something unrelated to salary (like if you switch the facet from "salary" to "japanese province", the "salary breakdown" heading becomes confusing).

**Comment by pwim** [comment]
Sure, I'm fine with removing the ability to customize the salary breakdown tab.
